# SwiftLint Configuration for VideoEditorClaude

# Paths to include during linting
included:
  - VEClaude

# Paths to exclude from linting
excluded:
  - Carthage
  - Pods
  - build
  - .build

# Rules to disable
disabled_rules:
  - trailing_whitespace
  - todo
  - line_length

# Rules to opt into
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Custom rule configurations
line_length:
  warning: 120
  error: 200

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - URL
    - x
    - y
    - z

# Custom rules
custom_rules:
  print_usage:
    name: "Print Usage"
    regex: "\\bprint\\("
    message: "Use proper logging instead of print statements"
    severity: warning

  force_cast:
    name: "Force Cast"
    regex: "as!"
    message: "Use safe casting with 'as?' instead of force casting"
    severity: error

  empty_line_after_guard:
    name: "Empty Line After Guard"
    regex: "guard[^\n]*\\{[^\n]*\\n[^\n]*(?!\\s*$)"
    message: "Add an empty line after guard statements"
    severity: warning

  mark_comment_spacing:
    name: "MARK Comment Spacing"
    regex: "//MARK:"
    message: "Add space after // in MARK comments"
    severity: warning

# File header template
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  VEClaude
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/

# Reporter type
reporter: "xcode"